Repository e-armadillo/getstartedvscodeplatformio, pull requests merged in 2020-09, with the labels that each got.

#2 PlatformIO Instalacion
  DocumentacionPlatformIO/InstalacionPlatformIO.md
  DocumentacionPlatformIO/Libraries.png
  DocumentacionPlatformIO/Main.png
  DocumentacionPlatformIO/NewProject.png
  DocumentacionPlatformIO/Projects.png
  codigo.ino
  hojadedatos
Labels: documentation

#1 Agregar Documentacion sensores
  codigo.ino
  hojadedatos
Labels: enhancement, proposed pullrequest

#3 Programacion Sensor DHT11 y comunicacion MQTT
  DocumentacionPlatformIO/InstalacionPlatformIO.md
  SensorTemperaturaHumedad/DHT11/.gitignore
  SensorTemperaturaHumedad/DHT11/.vscode/extensions.json
  SensorTemperaturaHumedad/DHT11/include/README
  SensorTemperaturaHumedad/DHT11/lib/README
  SensorTemperaturaHumedad/DHT11/platformio.ini
  SensorTemperaturaHumedad/DHT11/src/main.cpp
  SensorTemperaturaHumedad/DHT11/test/README
  SensorTemperaturaHumedad/DHT_MQTT/.gitignore
  SensorTemperaturaHumedad/DHT_MQTT/.vscode/extensions.json
  SensorTemperaturaHumedad/DHT_MQTT/include/README
  SensorTemperaturaHumedad/DHT_MQTT/lib/README
  SensorTemperaturaHumedad/DHT_MQTT/platformio.ini
  SensorTemperaturaHumedad/DHT_MQTT/src/main.cpp
  SensorTemperaturaHumedad/DHT_MQTT/test/README
  SensorTemperaturaHumedad/HojaDeDatosDHT11.pdf
  SensorTemperaturaHumedad/IlustracionDHT11.png
  SensorTemperaturaHumedad/Instalacion DHT11.md
  SensorTemperaturaHumedad/Libreria.png
  SensorTemperaturaHumedad/MonitorSerie.png
  SensorTemperaturaHumedad/Sensor.jpg
  SensorTemperaturaHumedad/Serie.png
  SensorTemperaturaHumedad/Terminal.png
  SensorTemperaturaHumedad/Upload.png
  SensorTemperaturaHumedad/ejemplo.png
  codigo.ino
Labels: documentation, enhancement

#4 Nodemcu environment mqtt
  SensorTemperaturaHumedad/DHT_MQTT/platformio.ini
  SensorTemperaturaHumedad/DHT_MQTT/src/main.cpp
Labels: proposed pullrequest
